Alfabet:
  exclude: MijnAFOefeningen

AudioTimed:
  exclude: MijnATOefeningen

AudioVideo:
  exclude: MijnAVOefeningen,test

AVRecorder:
  exclude: MijnAVROefeningen

Draaiom:
  exclude: MijnDOOefeningen,GO-decenas_antes.html,CLT_Sp10A_alles.htm

Getallen:
  exclude: MijnGTOefeningen

Invul1Per1:
  exclude: MijnInv1Oefening

Invullen:
  exclude: MijnInvOefening
  
JaNeeLijst:
  exclude: MijnJNOefeningen

JaNeePr1Per1:
  exclude: MijnJNP1Oefeningen

JaNeePrent:
  exclude: MijnJNPOefeningen

JuisteKolom:
  exclude: MijnJKOefeningen

JuisteLetter:
  exclude: MijnJLOefeningen

JuistePr1Per1:
  exclude: MijnJP1Oefeningen

JuistePrent:
  exclude: MijnJPOefeningen

JuisteWoord:
  exclude: MijnJWOefeningen

JuistFout:
  exclude: MijnJFOefeningen

Klemtoon:
  exclude: MijnKlOefeningen

KlikPrent:
  exclude: MijnKpOefeningen

Kruiswoord:
  exclude: MijnKwOefeningen

Leestekst:
  exclude: MijnLTOefeningen

LettersOrdenen:
  exclude: MijnLoOefeningen

Meerkeuze:
  exclude: MijnMKOefeningen

MeerkMJuist:
  exclude: MijnMKOefeningen

MeerkTest:
  exclude: MijnMktOefeningen

MeerkVast:
  exclude: MijnMkvOefeningen

PrentVolgordeS:
  exclude: MijnPVSOefeningen

Slepen:
  exclude: MijnSlOefeningen

Tonos:
  exclude: MijnTNOefeningen

Uitspraak:
  exclude: MijnUOefeningen

WoordVolgorde:
  exclude: MijnWvOefeningen

WoordVolgordeM:
  exclude: MijnWvMOefeningen

ZinsVolgorde:
  exclude: MijnZvOefeningen

ZinsVolgordeS:
  exclude: MijnZVSOefeningen
